engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
exclude_paths:
- "resources/lang/**"