engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - php
        - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
exclude_paths:
- "resources/lang/**"