language: php
sudo: false
php:
  - '7.0'
  - hhvm

install:
  - phpenv config-rm xdebug.ini
  - composer selfupdate
  - rm composer.lock
  - composer update --no-scripts
  - php artisan clear-compiled
  - php artisan optimize
  - php artisan env
  - mv -v .env.testing .env
  - php artisan env
  - ./test.sh --notest --reset

script:
  - phpunit