sudo: required
language: bash

# safelist
branches:
  only:
  - develop
  - master

services:
  - docker

env:
  - VERSION=4.8.2
  - CHANNEL=stable


jobs:
  include:
    - dist: xenial
      arch: amd64
      env: ARCH=amd64
      stage: build
      script: ./.deploy/docker/travis.sh
    - dist: xenial
      arch: amd64
      env: ARCH=arm
      stage: build
      script: ./.deploy/docker/travis.sh
    - dist: xenial
      arch: arm64
      env: ARCH=arm64
      stage: build
      script: ./.deploy/docker/travis.sh
    - dist: xenial
      arch: amd64
      stage: manifest
      script: ./.deploy/docker/manifest.sh