sudo: required
language: bash
env:
  - VERSION=4.8.1.8

dist: xenial

arch:
  - amd64
  - arm64

# safelist
branches:
  only:
  - develop
  - master

services:
  - docker

jobs:
  include:
    - os: linux
      env: ARCH_VERS=amd64
    - os: linux
      env: ARCH_VERS=arm64

script:
  # - .deploy/docker/travis.sh
  # enable experimental features.
  - echo $TRAVIS_DIST
  - echo $ARM_VERS