language: php
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

# safelist
branches:
  only:
  - develop
  - master

services:
  - docker

before_install:
  - docker build -t jc5x/ff-test-builds:develop .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jc5x/ff-test-builds