sudo: required
env:
  - VERSION=4.7.10
  matrix:
    - ARCH=arm
    - ARCH=arm64
    - ARCH=amd64

dist: xenial
# safelist
branches:
  only:
  - develop
  - master

services:
  - docker

script:
  # enable experimental features.
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - docker version -f '{{.Server.Experimental}}'
  - docker version
  - .deploy/docker/build-generic.sh
  - .deploy/docker/manifest.sh