language: php
sudo: required
language: bash
# safelist
branches:
  only:
  - develop
  - master

services:
  - docker

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t jc5x/ff-test-builds:develop .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jc5x/ff-test-builds