sudo: required
language: bash
env:
  - VERSION=4.7.12

dist: xenial

# safelist
branches:
  only:
  - develop
  - master

services:
  - docker

script:
  # build everything
  - .deploy/docker/build-amd64.sh
  - .deploy/docker/build-arm.sh
  - .deploy/docker/manifest.sh
