sudo: required
language: bash

# safelist
branches:
  only:
  - develop
  - master

services:
  - docker

jobs:
  include:
    - dist: xenial
      arch: amd64
      env: ARCH=amd64 VERSION=4.8.1.8
    - dist: xenial
      arch: arm64
      env: ARCH=arm64 VERSION=4.8.1.8

script:
  # - .deploy/docker/travis.sh
  # enable experimental features.
  - echo $TRAVIS_DIST
  - echo $ARCH_VERS
  - .deploy/docker/build-$ARCH.sh
  - docker build -t jc5x/firefly-iii:develop-arm64 -f Dockerfile.arm64 .