sudo: required
language: bash
dist: xenial
# safelist
branches:
  only:
  - develop
  - master

env:
  - VERSION=4.7.10

services:
  - docker

script:
  # enable experimental features.
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - docker version -f '{{.Server.Experimental}}'
  - docker version
  - .deploy/docker/build-amd64.sh
  - .deploy/docker/build-arm.sh
  - .deploy/docker/manifest.sh