version: '2'

services:
  firefly-db:
    volumes:
      - firefly-dev-storage:/var/lib/mysql
  firefly-app:
    environment:
      - INIT_DATABASE=yes
      - FF_APP_ENV=development

volumes:
  firefly-dev-storage:
    driver: local
